In [ ]:
#30.1.25
import pandas as pd
import numpy as np

In [8]:
#1.Create a 1D and 2D using Numpy , print its datatype, shape,dimension. 

In [64]:
arr1D=np.array([i for i in range(10)])
arr2D=np.array([[1,2,3],[4,5,6]],dtype='S')
print(arr1D.dtype,arr2D.dtype)
print(arr1D.shape,arr2D.shape) #(row,col)
arr5D=np.array([i for i in range(1,6)],ndmin=5)
print(arr5D.shape)

int32 |S1
(10,) (2, 3)
(1, 1, 1, 1, 5)


In [62]:
#2 i) random initialization 
arrR2D=np.random.rand(2,4)
print('{}\n{}'.format(arrR2D.shape,arrR2D))

(2, 4)
[[0.28694931 0.79448021 0.45679621 0.00091689]
 [0.14649018 0.13261598 0.11768445 0.78022948]]


In [84]:
#ii) Default initialization-linespace and arrange
arr=np.linspace(1,10,2) #No of point
arr1=np.arange(1,10,2) #Step size
print(arr)
print(arr1)

[ 1. 10.]
[1 3 5 7 9]


In [72]:
#iii) Print Diagonal values
print(arrR2D.diagonal())

[0.28694931 0.13261598]


In [74]:
#iv) Print First Element
print(arrR2D[0][0])

0.2869493093852846


In [80]:
#v) Print Last ELement
print(arrR2D[-1][-1])

0.7802294756029324


In [90]:
#vi) Print 2nd row and 2nd column Element 
print(arrR2D[1])
print(arrR2D[:,1])
print(arrR2D[1,1])

[0.14649018 0.13261598 0.11768445 0.78022948]
[0.79448021 0.13261598]
0.1326159849861379


In [94]:
#vii) Print No. of Elements 
print(arrR2D.size)

8


In [112]:
#3.Find the Determinant, Addition , Multiplication , Subraction , Division , Transpose, Cross Product , Dot product of a matrix
arr22A=np.random.rand(2,2) #np.array([[1,2],[3,4]])
arr22B=np.random.rand(2,2) #np.array([[-1,0],[-3,0]])
print('arrA:\n',arr22A,'\nAarrB:\n',arr22B)

arrA:
 [[0.45615033 0.56843395]
 [0.0187898  0.6176355 ]] 
AarrB:
 [[0.61209572 0.616934  ]
 [0.94374808 0.6818203 ]]


In [124]:
add=np.add(arr22A,arr22B)
print(add)

[[1.06824605 1.18536795]
 [0.96253788 1.2994558 ]]


In [126]:
mul=arr22A*arr22B
print(mul)

[[0.27920767 0.35068623]
 [0.01773284 0.42111642]]


In [128]:
sub=np.subtract(arr22A,arr22B)
print(sub)

[[-0.15594539 -0.04850005]
 [-0.92495828 -0.0641848 ]]


In [130]:
div=arr22A/arr22B
print(div)

[[0.74522712 0.92138535]
 [0.01990976 0.90586258]]


In [152]:
#Transpose
arr2DT=arr2D.transpose()
print(arr2DT,'\n',arr2D.T)

[[b'1' b'4']
 [b'2' b'5']
 [b'3' b'6']] 
 [[b'1' b'4']
 [b'2' b'5']
 [b'3' b'6']]


In [140]:
A=np.array([[1,2],[3,4]])
B=np.array([[-1,0],[-3,0]])

In [146]:
#dt-product
r1=np.dot(A,B)
r2=np.matmul(A,B)
r3=A@B
print(r1,'\n',r2,'\n',r3)

[[ -7   0]
 [-15   0]] 
 [[ -7   0]
 [-15   0]] 
 [[ -7   0]
 [-15   0]]


In [148]:
#cross product
r=np.cross(A,B)
print(r)

[ 2 12]


In [154]:
#determinant
detA=np.linalg.det(A)
print(detA)

-2.0000000000000004


In [164]:
#4. Print range values in 1D and 2D.
#5. Reshape an array. 
a=np.linspace(1,10,10)
b=np.linspace(1,20,20).reshape(2,10)

In [166]:
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [168]:
print(b)

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]]


In [190]:
#6.find the min, max  sum, mean, median mode and SD
from collections import Counter
print('min'.format(a.min()))
print(f'max:{a.max()}')
print('sum',a.sum())
print('mean',a.mean())
print('median',np.median(a))
print('std',np.std(a))
print('Mode',[key for key,val in Counter(a).items() if val==max(Counter(a).values())])#all have smae max fre=1

min
max:10.0
sum 55.0
mean 5.5
median 5.5
std 2.8722813232690143
Mode [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]


In [192]:
import statistics

In [194]:
print('mode',statistics.mode(a))

mode 1.0


In [196]:
'''7. Create a boolean mask for values greater than 5. 
Use the mask to filter out values less than or equal to 5. 
Count the number of values greater than 5.'''

'7. Create a boolean mask for values greater than 5. \nUse the mask to filter out values less than or equal to 5. \nCount the number of values greater than 5.'

In [198]:
mask=b>5
print(mask)

[[False False False False False  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]]


In [208]:
print(b[mask])
print(np.count_nonzero(mask))

[ 6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
15


In [202]:
'''8.Fancy Indexing 
Use fancy indexing to access elements at specific indices. 
Create a new array by selecting every other element. '''

'8.Fancy Indexing \nUse fancy indexing to access elements at specific indices. \nCreate a new array by selecting every other element. '

In [214]:
indix=[1,2,3,5]
print(a[indix])
print(b[1][[2,3,4]])

[2. 3. 4. 6.]
[13. 14. 15.]


In [218]:
x=a[::2]
print(x)

[1. 3. 5. 7. 9.]


In [206]:
'''9. structured array: 
Create a structured array to store information about students (name, age, and grade). 
Create a few sample students. 
Access and modify specific fields of the structured array. '''

'9. structured array: \nCreate a structured array to store information about students (name, age, and grade). \nCreate a few sample students. \nAccess and modify specific fields of the structured array. '

In [238]:
#TYPE-1
student_dtype=np.dtype([('Name','U20'),('Age','i4'),('grade','f4')])
students=np.array([('Abi',19,10.00),('Arjun',19,9.98),('Deepthi',19,9.98)],dtype=student_dtype)

In [240]:
print(students,students.dtype)

[('Abi', 19, 10.  ) ('Arjun', 19,  9.98) ('Deepthi', 19,  9.98)] [('Name', '<U20'), ('Age', '<i4'), ('grade', '<f4')]


In [248]:
students=np.insert(students,0,('Avanthika',19,10.00))

In [250]:
students[1][0]='Abirama varshini V'

In [252]:
print(students)

[('Avanthika', 19, 10.  ) ('Abirama varshini V', 19, 10.  )
 ('Abirama varshini V', 19,  9.98) ('Deepthi', 19,  9.98)]


In [254]:
import os
os.getcwd()

'C:\\Users\\DELL'

In [260]:
import pandas as pd

In [303]:
#10.Linear Regression 
df=pd.read_csv('study_data.csv')

In [305]:
print(df)

   Study Hours  Practice Tests  Score
0            2               1     60
1            3               2     65
2            4               2     70
3            5               3     75
4            6               3     80


In [307]:
y=df['Score']
print(y)

0    60
1    65
2    70
3    75
4    80
Name: Score, dtype: int64


In [309]:
X=df[['Study Hours','Practice Tests']]
print(X)

   Study Hours  Practice Tests
0            2               1
1            3               2
2            4               2
3            5               3
4            6               3


In [311]:
x=np.ones(5).reshape(5,1)

In [313]:
print(x)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [315]:
X=np.hstack((x,X))

In [319]:
print(X,X.T)

[[1. 2. 1.]
 [1. 3. 2.]
 [1. 4. 2.]
 [1. 5. 3.]
 [1. 6. 3.]] [[1. 1. 1. 1. 1.]
 [2. 3. 4. 5. 6.]
 [1. 2. 2. 3. 3.]]


In [323]:
def cal_normal_eq(X,y):
    Xt=X.T
    xin=Xt@X
    xinv=np.linalg.inv(xin)
    return xinv@Xt@y
W=cal_normal_eq(X,y)
print(W)

[ 5.00000000e+01  5.00000000e+00 -4.33431069e-13]
